[package]
name = "cook"
version = "0.11.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0", features = ["derive"] }
cooklang = "0.15"
anyhow = "1"
camino = { version = "1", features = ["serde1"] }
once_cell = "1.17"
cooklang-to-human = "0.15"
cooklang-to-cooklang = "0.15"
cooklang-to-md = "0.15"
serde_json = "1.0"
anstream = "0.6"
cooklang-fs = "0.15"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
serde = "1.0"
tabular = "0.2"
directories = "5"
serde_yaml = "0.9"
rust-embed = "8"
reqwest = { version = "0.11", features = ["blocking", "json"] }
tokio = { version = "1", features = ["full"] }
axum = { version = "0.6" }
tower = { version = "0.4", features = ["util"] }
tower-http = { version = "0.4", features = ["fs", "trace", "cors"] }
futures = "0.3"
mime_guess = "2.0"
open = "5.0"
openssl = { version = "0.10", features = ["vendored"] }
