#!/usr/bin/env bash
# Build a .deb of cookcli from this checkout.
#
# Usage:
#   packaging/debian/build-deb.sh
#
# Builds the release binary with cargo, then assembles the package with
# dpkg-deb: the `cook` binary, bash/zsh/fish completions generated by it, the
# copyright file and the README. Depends: is computed by dpkg-shlibdeps from
# the binary itself.
#
# Like the RPM, the binary is built without `self-update`: a packaged binary
# must be updated by apt, not replace itself from GitHub releases.
#
# The package works on any distribution whose glibc is at least the one it was
# built against, so build it on the oldest one you want to support — CI uses
# ubuntu:22.04, which covers Ubuntu 22.04+ and Debian 12+.
#
# Requires: cargo (a rustup toolchain — the distributions' own rustc is too old
# for this crate), dpkg-dev, and the compiled web assets
# (npm ci && npm run build-css && npm run build-js).
#
# Environment:
#   DEB_REVISION    Debian revision appended to the version (default: 1)
#   DEB_MAINTAINER  Maintainer: field (default: the project's issue tracker)
#
# Output: dist/deb/cookcli_<version>-<revision>_<arch>.deb
set -euo pipefail

repo=$(cd "$(dirname "$0")/../.." && pwd)
cd "$repo"

for tool in cargo dpkg-deb dpkg-shlibdeps dpkg-architecture; do
    command -v "$tool" >/dev/null || { echo "missing tool: $tool" >&2; exit 1; }
done
for asset in static/css/output.css static/js/editor.bundle.js; do
    if [[ ! -f $asset ]]; then
        echo "missing $asset — run: npm ci && npm run build-css && npm run build-js" >&2
        exit 1
    fi
done

version=$(sed -n 's/^version = "\(.*\)"$/\1/p' Cargo.toml | head -1)
revision=${DEB_REVISION:-1}
maintainer=${DEB_MAINTAINER:-"CookCLI maintainers <https://github.com/cooklang/cookcli/issues>"}
arch=$(dpkg-architecture -qDEB_HOST_ARCH)
package="cookcli_${version}-${revision}_${arch}.deb"

echo ">> building cook $version (without self-update)"
cargo build --release --locked --no-default-features --features server,import,lsp,sync
bin="${CARGO_TARGET_DIR:-target}/release/cook"

umask 022
work=$(mktemp -d)
trap 'rm -rf "$work"' EXIT
root="$work/root"

install -D -m 0755 "$bin" "$root/usr/bin/cook"

# Shell completions, generated by the binary itself, at the paths each shell's
# Debian package searches.
install -d "$root/usr/share/bash-completion/completions" \
    "$root/usr/share/zsh/vendor-completions" \
    "$root/usr/share/fish/vendor_completions.d"
"$bin" completions bash > "$root/usr/share/bash-completion/completions/cook"
"$bin" completions zsh > "$root/usr/share/zsh/vendor-completions/_cook"
"$bin" completions fish > "$root/usr/share/fish/vendor_completions.d/cook.fish"

doc="$root/usr/share/doc/cookcli"
install -D -m 0644 README.md "$doc/README.md"
# Machine-readable copyright file, with the license text indented and blank
# lines written as " ." as the format requires.
{
    echo "Format: https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/"
    echo "Upstream-Name: cookcli"
    echo "Source: https://github.com/cooklang/cookcli"
    echo
    echo "Files: *"
    echo "Copyright: $(sed -n 's/^Copyright (c) //p' LICENSE | head -1)"
    echo "License: MIT"
    sed -e '1,/^Copyright/d' LICENSE | sed -e '1{/^$/d}' -e 's/^$/./' -e 's/^/ /'
} > "$doc/copyright"

# dpkg-shlibdeps insists on a debian/control next to where it runs, even
# though only the binary's shared libraries matter here.
mkdir -p "$work/debian"
printf 'Source: cookcli\n\nPackage: cookcli\nArchitecture: any\n' > "$work/debian/control"
depends=$(cd "$work" && dpkg-shlibdeps -O root/usr/bin/cook 2>/dev/null \
    | sed -n 's/^shlibs:Depends=//p')
[[ -n $depends ]] || { echo "dpkg-shlibdeps found no dependencies" >&2; exit 1; }

installed_size=$(du -sk "$root" | cut -f1)

install -d "$root/DEBIAN"
cat > "$root/DEBIAN/control" <<EOF
Package: cookcli
Version: ${version}-${revision}
Architecture: ${arch}
Maintainer: ${maintainer}
Installed-Size: ${installed_size}
Depends: ${depends}
Section: utils
Priority: optional
Homepage: https://cooklang.org/cli/
Description: Command-line interface for managing Cooklang recipes
 CookCLI is a command-line interface for managing and working with Cooklang
 recipes: parse and render recipes, scale ingredients, generate shopping lists
 organized by aisle, keep a pantry, import recipes from websites, serve the web
 UI, run a language server for editors, and more.
 .
 This package is built without the self-update feature: updates come from the
 package manager.
EOF

mkdir -p dist/deb
dpkg-deb --build --root-owner-group -Zxz "$root" "dist/deb/$package" >/dev/null
dpkg-deb --info "dist/deb/$package"
echo "dist/deb/$package"
