# CookCLI spec for Fedora (and other RPM-based distributions).
#
# The package builds from the release source tarball (Source0), which ships the
# compiled web assets, so Node.js is not needed at build time. Crate
# dependencies are vendored into Source1 (see packaging/fedora/README.md) and
# the build runs fully offline, as a build root must.
#
# The `self-update` feature is deliberately left out: a packaged binary must be
# updated by the package manager, not replace itself from GitHub releases.
# `cook update` is therefore absent from this build; use `dnf upgrade` instead.
#
# The `sync` feature (CookCloud login/logout) compiles SQLite in via
# libsqlite3-sys' `bundled` feature, which cooklang-sync-client hardcodes.
# Build without it with `rpmbuild --without sync` if that is a problem for
# your target distribution.
%bcond_without sync

Name:           cookcli
# build-rpm.sh substitutes the version from Cargo.toml, so this only has to be
# right when building the spec directly with rpmbuild.
Version:        0.35.0
Release:        1%{?dist}
Summary:        Command-line interface for managing Cooklang recipes

License:        MIT
URL:            https://cooklang.org/cli/
Source0:        https://github.com/cooklang/cookcli/releases/download/v%{version}/cook-%{version}-source.tar.gz
# Vendored crate sources, generated from Source0 with `cargo vendor` (see
# packaging/fedora/README.md). Not tied to a particular architecture.
Source1:        cookcli-%{version}-vendor.tar.xz

# rpmbuild resolves these against installed packages, so the build root needs
# the distribution's rust/cargo — a rustup toolchain on PATH does not satisfy
# them. gcc: libsqlite3-sys (bundled) and other -sys crates compile C code.
BuildRequires:  gcc
BuildRequires:  rust
BuildRequires:  cargo

# The release profile strips the binary; there is nothing left to split off.
%global debug_package %{nil}

%description
CookCLI is a command-line interface for managing and working with Cooklang
recipes: parse and render recipes, scale ingredients, generate shopping lists
organized by aisle, keep a pantry, import recipes from websites, serve the web
UI, run a language server for editors, and more.

This package is built without the self-update feature: updates come from the
package manager.

%prep
%setup -q -n cookcli-%{version} -a 1

%build
%set_build_flags
export CARGO_NET_OFFLINE=true

FEATURES="server,import,lsp"
%if %{with sync}
FEATURES="$FEATURES,sync"
%endif

cargo build --release --locked --offline --no-default-features --features "$FEATURES"

%install
install -Dpm 0755 target/release/cook %{buildroot}%{_bindir}/cook

# Shell completions, generated by the binary itself.
install -d -m 0755 %{buildroot}%{_datadir}/bash-completion/completions
target/release/cook completions bash > %{buildroot}%{_datadir}/bash-completion/completions/cook

install -d -m 0755 %{buildroot}%{_datadir}/zsh/site-functions
target/release/cook completions zsh > %{buildroot}%{_datadir}/zsh/site-functions/_cook

install -d -m 0755 %{buildroot}%{_datadir}/fish/vendor_completions.d
target/release/cook completions fish > %{buildroot}%{_datadir}/fish/vendor_completions.d/cook.fish

%files
%license LICENSE
%doc README.md
%{_bindir}/cook
%{_datadir}/bash-completion/completions/cook
%{_datadir}/zsh/site-functions/_cook
%{_datadir}/fish/vendor_completions.d/cook.fish

%changelog
* Fri Sep 04 2026 CookCLI maintainers - 0.35.0-1
- Initial RPM packaging, generated from the release sources.
