[fruit and veg]
apples
aubergine
avocado
avocados
baby corn
bamboo shoots
bananas
beetroots
bell pepper
bell peppers
broccoli
carrot
carrots
cauliflower
celeriac
celery
cherry tomatoes
Chinese cabbage
clementine
coconut
coriander
courgettes
cucumber
dill
fresh basil
fresh coriander
fresh oregano
garlic
garlic clove
ginger
grapes
lemon
lime
mango
melon
mushrooms
nectarines
onion
onions
peaches
pears
potatoes
raspberries
red bell pepper
red chilli
red onion
red onions
red peppers
ripe tomatoes
salad leaves
scallions
shallot
spinach
spring onions
strawberries
thai basil
thyme
tomatoes

[milk and dairy]
butter
cheddar cheese
curd cheese
egg
eggs
feta
fresh mozzarella
grated mozzarella
milk
mozzarella cheese|mozzarella
parmesan cheese|parmesan
soft cheese
sour cream

[meat and seafood]
bacon
chicken fillets
chicken thighs
corn beef
firm tofu
lamb
lamb chops
parma ham
prawns
rashers
smoked salmon
whole chicken

[breads and baked goods]
apple lattice pie
biscuits
breadcrumbs
breakfast biscuits
croissant
profiteroles
tortillas

[tinned goods and baking]
baked beans
cannellini beans
chopped tomato
coconut milk
corn starch
flour
fresh yeast
pickles
plain flour
redcurrant jelly
strained kimchi
strong white flour
tin tomatoes
tinned pineapples
tinned tomatoes
tipo zero flour

[packaged goods, pasta and sauces]
apple crisps
arborio rice
black tea
caster sugar
chicken broth
chocolate bars
chocolate spread
coffee
cooked rice
crackers
crisps
dates
dried apricots
dried plums
frozen peas
green curry paste
jasmine rice
linguine pasta
mayonnaise
oats
pistachios
pumpkin seeds
raisins
sugar
tomato paste
vegetable stock
water

[dried herbs and spices]
bay leaves
black pepper
cayenne pepper
dried oregano
dried sage
fennel seeds
flaky salt
garlic powder
ground cinnamon
ground coriander
ground cumin
onion powder
palm sugar
paprika
pepper
poultry seasoning
saffron threads
salt
sea salt
smoked paprika
star anise
white pepper

[oils and dressings]
balsamic glaze
chilli oil
Chinese cooking wine
cider
coconut oil
Dijon mustard
extra virgin olive oil
fish sauce
honey
Marmite
oil
olive oil
oyster sauce
peanut oil
red wine vinegar
rice wine vinegar
sesame oil
soy sauce
white vinegar
white wine
