[fruit and veg]
apples
bananas
grapes
nectarines
peaches
pears
raspberries
strawberries
blueberries
lemon
lime
clementine
mango
melon

avocado | avocados
cucumber
courgettes
aubergine
spinach
salad leaves
broccoli
cauliflower
celery
celeriac
Chinese cabbage

onion | onions
red onion | red onions
shallot
scallions
spring onions

potatoes
beetroots
carrot | carrots

bell pepper | bell peppers
red bell pepper
red peppers

cherry tomatoes
ripe tomatoes
tomatoes

mushrooms
coconut
baby corn
bamboo shoots

garlic | garlic clove
ginger
red chilli | fresh red chilli

coriander | fresh coriander
fresh basil
thai basil
fresh oregano
dill
thyme

[milk and dairy]
milk
butter
egg | eggs
sour cream

cheddar cheese
curd cheese
feta
fresh mozzarella
grated mozzarella
mozzarella cheese | mozzarella
parmesan cheese | parmesan
soft cheese

[meat and seafood]
lamb chops
lamb
bacon
corn beef
parma ham
rashers

chicken fillets
chicken thighs
whole chicken

prawns
smoked salmon

firm tofu

[breads and baked goods]
apple lattice pie
biscuits
breakfast biscuits
breadcrumbs
croissant
profiteroles
tortillas
bread

[tinned goods and baking]
cannellini beans
baked beans

tin tomatoes | tinned tomatoes | chopped tomato
tinned pineapples

coconut milk
pickles
strained kimchi
redcurrant jelly

flour | plain flour
strong white flour
tipo zero flour
corn starch
fresh yeast

[packaged goods, pasta and sauces]
arborio rice
jasmine rice
cooked rice
linguine pasta

oats
sugar | caster sugar

green curry paste
tomato paste
chocolate spread
mayonnaise
chicken broth
vegetable stock

coffee
black tea
water

apple crisps
chocolate bars
crackers
crisps
dates
dried apricots
dried plums
pistachios
pumpkin seeds
raisins
frozen peas

[dried herbs and spices]
salt | sea salt | flaky salt
black pepper | pepper
white pepper

bay leaves
cayenne pepper
dried oregano
dried sage
fennel seeds
garlic powder
ground cinnamon
ground coriander
ground cumin
onion powder
palm sugar
paprika
smoked paprika
poultry seasoning
saffron threads
star anise

[oils and dressings]
olive oil | extra virgin olive oil | oil
coconut oil
peanut oil
sesame oil
chilli oil

Dijon mustard
honey
Marmite
balsamic glaze

soy sauce
fish sauce
oyster sauce

red wine vinegar
rice wine vinegar
white vinegar

Chinese cooking wine
white wine
cider
