water = "unlim"

["spice rack"]
"black pepper" = "200%g"
"fennel seeds" = "some"
"ground cinnamon" = "some"
"ground cumin" = "50%g"
salt = "1%kg"
"sea salt" = "500%g"
"smoked paprika" = "50%g"

[fridge]
butter = { quantity = "250%g", expire = "2026-04-15" }
eggs = { quantity = "12", bought = "2026-03-07" }
milk = "1%l"
"parmesan cheese" = "200%g"
"sour cream" = "200%ml"

[freezer]
"frozen peas" = "500%g"

[pantry]
"arborio rice" = "1%kg"
"cannellini beans" = "2%tins"
"coconut milk" = "2%tins"
"extra virgin olive oil" = "500%ml"
flour = "1%kg"
"jasmine rice" = "1%kg"
oats = "500%g"
"olive oil" = "750%ml"
"soy sauce" = "250%ml"
sugar = "1%kg"
"tinned tomatoes" = "0"
"tipo zero flour" = "1%kg"
"vegetable stock" = "1%l"

[garden]
"fresh basil" = "unlim"
"fresh oregano" = "unlim"
thyme = "unlim"
