water = "unlim"

[fridge]
butter = { quantity = "250%g", expire = "2026-04-15" }
eggs = { quantity = "12", bought = "2026-03-07" }
milk = { quantity = "2%l" }
"parmesan cheese" = { quantity = "200%g" }
"sour cream" = { quantity = "200%ml" }

[garden]
"fresh basil" = { quantity = "unlim" }
"fresh oregano" = { quantity = "unlim" }
thyme = { quantity = "unlim" }

[pantry]
"arborio rice" = { quantity = "1%kg" }
"cannellini beans" = { quantity = "2%tins" }
"coconut milk" = { quantity = "2%tins" }
"extra virgin olive oil" = { quantity = "500%ml" }
flour = { quantity = "1%kg" }
"jasmine rice" = { quantity = "1%kg" }
oats = { quantity = "500%g" }
"olive oil" = { quantity = "750%ml" }
"soy sauce" = { quantity = "250%ml" }
sugar = { quantity = "1%kg" }
"tinned tomatoes" = { quantity = "0" }
"tipo zero flour" = { quantity = "1%kg" }
"vegetable stock" = { quantity = "1%l" }

["spice rack"]
"black pepper" = { quantity = "200%g" }
"fennel seeds" = { quantity = "some" }
"ground cinnamon" = { quantity = "some" }
"ground cumin" = { quantity = "50%g" }
salt = { quantity = "1%kg" }
"sea salt" = { quantity = "500%g" }
"smoked paprika" = { quantity = "50%g" }
